# Generated by Django 4.2.9 on 2025-12-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcmapping',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pc_mapping', to='students.student'),
        ),
        migrations.AddField(
            model_name='batch',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('semester', 'name')},
        ),
    ]
