# Generated by Django 4.2.9 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('hour_slot', models.IntegerField()),
                ('subject_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='accounts.user')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_timetable_slots', to='core.semester')),
            ],
            options={
                'db_table': 'faculty_timetable_slots',
                'ordering': ['semester__number', 'day_of_week', 'hour_slot'],
                'unique_together': {('faculty', 'semester', 'day_of_week', 'hour_slot')},
            },
        ),
    ]
