# Generated by Django 4.2.9 on 2026-03-08 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_facultytimetableslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_locked', models.BooleanField(default=False)),
                ('internet_blocked', models.BooleanField(default=False)),
                ('usb_disabled', models.BooleanField(default=False)),
                ('whitelisted_apps', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_state', to='core.batch')),
            ],
            options={
                'db_table': 'control_states',
            },
        ),
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('lock_pc', 'Lock PC'), ('unlock_pc', 'Unlock PC'), ('block_internet', 'Block Internet'), ('unblock_internet', 'Unblock Internet'), ('enable_usb', 'Enable USB'), ('disable_usb', 'Disable USB'), ('app_whitelist', 'App Whitelist')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_commands', to='core.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
