# Generated by Django 6.0 on 2025-12-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject_covered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
