# Generated by Django 6.0 on 2025-12-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancesession_remarks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='subject_covered',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='status',
        ),
    ]
